- google/generativeai/__init__.py
I think this is pretty conventional. Users should be able to:
```python
import google.generativeai as palm
print(palm.__version__)`
```
Change-Id: Ide7299f3a4d7a9017cf05fa42d78126a5c4bacf7
> Add `__version__` to top-level package.

- setup.py
Python 3.8 was included for Colab, and that's how we were testing it. 3.8 is in end-of-life-secutrity-patches-only mode. Colab has moved to 3.10.
For: https://github.com/google/generative-ai-python/issues/13
> Drop python 3.8

- google/generativeai/discuss.py
- tests/test_discuss.py
The created message should be a `dict`.
> Fix errors caused by setting ChatResponse.last

- docs/build_docs.py
This prevents the auto-linking to the GLAPI docs root too.
> Fix minor typo.

- google/generativeai/discuss.py
This PR tries to fix a mystery string interpolation when the number of `examples` is odd when using `chat`.
Before the fix:
```
ValueError: You must pass `Primer` objects, pairs of messages, or an *even* number of messages, got: 
{len(primers)} messages
```
After the fix:
```
ValueError: You must pass `Primer` objects, pairs of messages, or an *even* number of messages, got: 
1 messages
```
> Try to fix mystery string interpolation

- google/generativeai/models.py
- tests/test_models.py
Right now we require model names to be specified as `"models/type-size-version"` (with the `models/` prefix), but that seems slightly unintuitive. This change adds the `models/` prefix if it detects the expected *bare* model string (e.g. `foo-bar-001`).
Adds `test_models.py` too.
Before:
```python
model = palm.get_model('models/text-bison-001')
```
After:
```python
model = palm.get_model('text-bison-001')
```
> Support bare model names in `palm.get_model`

- README.md
In https://github.com/google/generative-ai-docs/issues/63 the user pointed out that we don't document Python support.
This badge uses the latest PyPI package, so should be future-proof as we move things around.
> Add Python support to README

- google/generativeai/__init__.py
the usage `model = palm.get_model('chat-bison-001') ` which the code comments provided is incorrect.
It should be model = palm.get_model('models/chat-bison-001')  to run correctly.
> Fix: fix comments generative-ai-python/google/generativeai/__init__.py

- .github/labeler.yml
- .github/workflows/labeler.yml
- .github/workflows/remove-issue-labels.yml
- .github/workflows/remove-pr-labels.yml
1. Add "awaiting-review" to all opened PRs
2. Remove "status:X" labels when an issue is closed
3. Remove "status:X" labels when a PR is closed
> Automatically add and remove specific labels

- google/generativeai/discuss.py
- google/generativeai/models.py
- google/generativeai/text.py
- tests/test_models.py
> Addition of docstrings to the files

- .github/workflows/stale.yml
Adding github action workflow to mark stale issues and prs. This stale management workflow will add stale label and post reminder message after 14 days of inactivity and further close issue/pr after another 14 days of inactivity. We can also override stale action by adding override-stale label. Thanks! cc @google/gtech-llm-support
> Adding github action workflow to mark stale issues and prs.

- google/generativeai/types/safety_types.py
Add more options to the `{option: enum}` dicts for safety settings. 
The full enum item name should always be in the dict.
> Exapand safety enum options, b/301993890

- .editorconfig
- .gitignore
- pyproject.toml
These are helpful for persisting style preferences across IDEs & tools. e.g. by default PyCharm likes to follow PEP8, so dumps a *heap* of errors.
Also ignore idea project files.
> Add basic editor configs

- google/generativeai/types/model_types.py
Revert accidental change to the public api-surface:.
> Restore ModelNameOptions for backwards compatibility.

- google/generativeai/types/model_types.py
- tests/test_models.py
Add support for tabs when loading Sheets URLs
CSV URL supports it, and silently dropping the tab seems less than ideal, so this seems like an easy fix.
Choose one: Bug fix | Feature request
> Support specific tabs when loading Google Sheets

- docs/build_docs.py
GLAPI members defined in a versioned package (e.g. `v1beta3`) were generating an incorrect URL for the "view on github" link.
To test the regex I ran it on a suspended instance of the script:
```
diff -u <(egrep -Iir 'generativelanguage_\w+\.types' docs/api/google/ai/generativelanguage/ --include=*.md) \
<(egrep -Iir 'generativelanguage_\w+.types' docs/api/google/ai/generativelanguage/ --include=*.md)
```
Output [here](http://go/paste/6300090913259520), but it only matched `<a href />`s.
> Fix source URLs for `glm.*` members.

- tests/test_operations.py
`refresh()` can be called with args, so accept arbitrary args for the fake implementation.
This was an issue internally, where refresh appears to be called with args. This fix allows this test class to be run internally too.
> Allow `refresh()` to take args

- google/generativeai/generative_models.py
`async def count_tokens(
self,
request: Optional[Union[generative_service.CountTokensRequest, dict]] = None,
*,
model: Optional[str] = None,
contents: Optional[MutableSequence[content.Content]] = None,
retry: OptionalRetry = gapic_v1.method.DEFAULT,
timeout: Union[float, object] = gapic_v1.method.DEFAULT,
metadata: Sequence[Tuple[str, str]] = (),
`
if you don't use keyword args : model=model, contents=contents,  but position args, this will lead to : TypeError: count_tokens() takes from 1 to 2 positional arguments but 3 were given
- [x ] I have performed a self-review of my code.
- [x ] I have added detailed comments to my code where applicable.
- [x ] I have verified that my change does not break existing code.
- [x ] My PR …
> fix TypeError in count_tokens & count_tokens_async

- README.md
Fix `Javascript` typo to `Python` in README.md
Avoids confusion in the README since this is the Python SDK. 
Documentation
> Fix Javscript -> Python typo in README.md

- google/generativeai/types/generation_types.py
- tests/test_generative_models_async.py
solve aiter, anext not exit in pthon 3.9 ,but maybe there is a better way? 
bug fix
> aiter, anext not exist error

- google/generativeai/types/generation_types.py
while question was blocked by api, the parts is an empty list [],  so the exp: 
if len(parts) > 1 or "text" not in parts[0]:
will raise list index out of range, but not ValueError
check parts before parts[0]
Bug fix
> Fix: List Index out out range with empty parts []

- google/generativeai/generative_models.py
- google/generativeai/types/content_types.py
Update  `ChatSession.send_message` to  check for empty `contents`. If `contents` is  empty a `TypeError` (Same behavior as `GenerativeModel.generate_content`)
Fixing issue : #133 
Choose one: Bug fix
> fix: handle empty string in ChatSession.send_message

- docs/build_docs.py
GRPC has a circular import that's skipped by the typing flag. Move imports to make the build pass.
in grpc/_typing.py:
```
if TYPE_CHECKING:
from grpc import ServicerContext
from grpc._server import _RPCState
```
> Fix build docs.

- docs/build_docs.py
- google/generativeai/types/generation_types.py
Error message style fix
Thank you very much for developing this great library.
I saw the error message
```
File "/.../venv/lib/python3.11/site-packages/google/generativeai/types/generation_types.py", line 328, in text
raise ValueError(
ValueError: The `response.text` quick accessor only works for simple (single-`Part`) text responses. This response is not simple text.Use the `result.parts` accessor or the full `result.candidates[index].content.parts` lookup instead.
```
and found `text.Use` (no space!)
Choose one: Other
> More readable error message

- .github/workflows/test_pr.yaml
- setup.py
Enable testing with python 3.12
3.12 is the latest version of python and is now supported by the underlying GAPIC and auth libraries. 
https://devguide.python.org/versions/
Feature request
- [x ] I have performed a self-review of my code.
> Add python 3.12 support.

- README.md
- google/generativeai/notebook/cmd_line_parser.py
- google/generativeai/notebook/magics.py
- google/generativeai/notebook/text_model.py
- tests/notebook/test_magics_engine.py
- tests/notebook/text_model_test.py
Adds some aliases for the commands too:
* `%%palm` still works, for backwards compat
* `%%llm` as a generic magic
* `%%gemini` as an analogue to `%%palm`
Need to work with the new API and new models.
Choose one: New feature
> Update notebook magics to work with Gemini

- google/generativeai/embedding.py
- google/generativeai/notebook/lib/llmfn_outputs.py
- google/generativeai/notebook/magics_engine.py
- google/generativeai/text.py
- google/generativeai/types/generation_types.py
When a response has been blocked, the API will return a `Candidate` (with `finish_reason`, `safety_ratings`, etc) that does not have any `Part`s.  Given blocking is common enough, and we can identify this case, I've added a more explicit (and helpful?) error message to guide users if this happens.
LMK (or just push) if you think this could be worded clearer.
This should also fix the `TypeError: argument of type 'Part' is not iterable` error thrown in another (unknown?) case.
> Add a more explicit error when no `parts` returned

- .gitignore
- google/generativeai/client.py
- google/generativeai/models.py
- google/generativeai/retriever.py
- google/generativeai/types/embedding_types.py
- google/generativeai/types/retriever_types.py
- google/generativeai/utils.py
- tests/test_retriever.py
- tests/test_retriever_async.py
Change-Id: I5c4f35238f3bc0bbc798abd72cf824ebe1103152
Adding Semantic Retriever Python Client Library.
> Semantic retriever

- google/generativeai/retriever.py
- google/generativeai/types/retriever_types.py
- tests/test_retriever.py
- tests/test_retriever_async.py
1. The `list` methods should return iterables of Corpus/Document/Chunk objects, and not expose the page-token.
2. Add `decode_document` and `decode_chunk` for use Everywhere the API returns a corpus or document.
> Fix list methods, add decode functions.

- .gitignore
- google/generativeai/answer.py
- google/generativeai/types/answer_types.py
- tests/test_answer.py
Change-Id: Ia95d8b2c48506f843f765c0546e848b46f6d8d32
Adding AQA API (Python)
> Adding AQA (GenerateAnswer).

- google/generativeai/generative_models.py
- google/generativeai/types/generation_types.py
- tests/test_generation.py
- tests/test_generative_models.py
Added a `__repr__` method to `GenerateContentResponse` and `ChatSession`. (WIP PR 🚧 for closes #173 )
Improve DX when debugging the code by being able to reproduce `response` and `chat` objects from the `repr` methods.
Feature request
> Implement __repr__ for GenerateContentResponse and ChatSession

- google/generativeai/generative_models.py
Now using the send_message_async method will cause an error ` object GenerateContentResponse can't be used in 'await' expression `
Running using an asynchronous method, just upgrading the library caused my entire project to not run properly
Bug fix 
-  I have performed a self-review of my code.
-  I have added detailed comments to my code where applicable.
-  I have verified that my change does not break existing code.
-  My PR is based on the latest changes of the main branch (if unsure, please run `git pull --rebase upstream main`).
-  I am familiar with the [Google Style Guide](https://google.github.io/styleguide/) for the language I have coded in.
-  I have read through the [Contributing Guide](https://github.com/google/generative-ai-python/blob/main/CONTRIBUTING.md) and signed the …
> The send_message_async method should call the asynchronous method generate_content_async

- docs/build_docs.py
- google/generativeai/__init__.py
- google/generativeai/client.py
- google/generativeai/files.py
- google/generativeai/generative_models.py
- google/generativeai/types/__init__.py
- google/generativeai/types/content_types.py
- google/generativeai/types/file_types.py
- google/generativeai/types/generation_types.py
- setup.py
WIP
When this is done, the code below should work
```
pip install -U git+https://github.com/MarkDaoust/generative-ai-python@files
```
```
pip install -U git+https://github.com/google-generativeai-python
```
```
import google.generativeai as genai
genai.configure(api_key="...")
f = genai.upload_file(path="image.png")
m = genai.GenerativeModel(model_name="models/gemini-1.5-pro")
response = m.generate_content(["hello? Pleasecdescribe this file:", f])
print(response.text)
```
> Add initial prototype supporting the files API

- google/generativeai/types/generation_types.py
Fix incorrect reference to self.candidates[0].parts, self.candidates[0].parts[0].text
#234 
self.candidates[0].parts to self.candidates[0].content.parts
self.candidates[0].parts[0].text to self.candidates[0].content.parts[0].text
miss leading
> Fix incorrect reference to self.candidates[0].parts, self.candidates[0].parts[0].text

- google/generativeai/__init__.py
- google/generativeai/client.py
- google/generativeai/files.py
- google/generativeai/generative_models.py
- google/generativeai/types/file_types.py
Add support for additional methods for files SDK
> Add additional functionalities with files SDK

- README.md
Remove PaLM info; direct folks to the cookbook and ai.google.dev to reduce information overlap, and so we have fewer things to maintain.
> Simply the Python SDK README

- google/generativeai/answer.py
- google/generativeai/generative_models.py
- google/generativeai/types/content_types.py
- setup.py
- tests/test_generative_models.py
- tests/test_typing_extensions.py
1. Update dependency of `glm` package to use [`0.6.1`](https://github.com/googleapis/google-cloud-python/releases/tag/google-ai-generativelanguage-v0.6.1).
2. proto def for `GenerateContentRequest` lists `system_instruction` in singular as the field is not repeated. This is consistent with the latest release(glm==0.6.1)
3. Import `TypedDict` from `typing_extensions`
> Sdk update to use glm 0.6.1

- google/generativeai/generative_models.py
- tests/test_generative_models.py
Add `system_instruction` to the repr of  `GenerativeModel`
Model repr has all the fields set at construction-time. sysint should be there too.
> Add `system_instruction` to model repr

- google/generativeai/notebook/text_model.py
Picked this up when adding missing tests on the internal copy. I think the failure is spurious but this fix is easy enough ¯\\\_(ツ)\_/¯
> Fix an internal test failure

- google/generativeai/types/generation_types.py
Adding JSON mode. Users can specify `application/json` to the `response_mime_type` parameter for `generate_content`.
Fixes: https://github.com/google/generative-ai-python/issues/137
> Add JSON mode

- google/generativeai/types/generation_types.py
These are all non-required so mark the typed dict as such.
> Allow incomplete GenerationConfigDict

- google/generativeai/responder.py
Moved code related to function calling from `content_types.py` to `responder.py`. Let me know if this is the correct that is moved out. Once we've confirmed this is what we want to move out, I'll remove that code from `content_types.py`.
Keep function calling separate from `content_types.py`.
> Responder: Copy function calling code into responder.py

- google/generativeai/types/file_types.py
a function was defined twice with same body. location is google.generativeai.types.file_types.File.update_time.
It doesn't solve any specific problem but it cleans the code a bit
other
> update_time defined twice hence removing once.

- google/generativeai/types/model_types.py
This was exposing the `{name}` when it raised.
> Add f to f-string

- google/generativeai/types/content_types.py
- google/generativeai/types/generation_types.py
- setup.py
- tests/test_content.py
- tests/test_generation.py
```
class Person(typing.TypedDict):
name: str
birthday: str
favorite_food: str
m = genai.GenerativeModel(model_name="gemini-1.5-pro-latest")
result = m.generate_content(
"describe a person",
generation_config={
"response_mime_type": "application/json",
"response_schema": Person},
)
```
> Improve schema support

- google/generativeai/client.py
This is causing a conflict with colab: colab's api_endpoint redirectsthrough localhost, and the redirector doesn't allow the discovery service through.
> Revert "Use api_endpoint for uploads (#330)"

- google/generativeai/client.py
- google/generativeai/files.py
Add support for resumable uploads by following the MediaFileUpload class in Python:
https://googleapis.github.io/google-api-python-client/docs/epy/googleapiclient.http.MediaFileUpload-class.html
Add some pydocs to clarify what the parameters specified are. Confirmed this is working locally:
> Add support for resumable uploads for File API

- CONTRIBUTING.md
- google/generativeai/answer.py
- google/generativeai/client.py
- google/generativeai/generative_models.py
- google/generativeai/models.py
- google/generativeai/types/permission_types.py
- tests/notebook/text_model_test.py
1. **Documentation and Error Messages**: Improved clarity and accuracy in documentation and error messages across multiple files. This includes providing more descriptive error messages and consistent usage examples to help developers better understand code functionalities and constraints.
2. **Typo Corrections**: Fixed typos in comments and function names, notably correcting `get_dafault_permission_client` to `get_default_permission_client` and its asynchronous counterpart in `client.py` and `types/permission_types.py`. These changes prevent potential bugs and improve overall code quality.
- **`generative_models.py`**:
- Corrected a typo from "equvalents" to "equivalents".
- Updated example usage to use a consistent model path format (`'models/gemini-pro'`), aligning with changes in …
> Fix bugs, improve code clarity, and enhance overall reliability across several files.

- google/generativeai/types/generation_types.py
Fixes: https://github.com/google-gemini/generative-ai-python/issues/139
> Add GenerateContentResponse.to_dict()

- google/generativeai/generative_models.py
- tests/test_generative_models.py
Fixes: https://github.com/google-gemini/generative-ai-python/issues/326
> Allow count_tokens with no `contents`.

- google/generativeai/generative_models.py
- google/generativeai/types/generation_types.py
- tests/test_generation.py
- tests/test_generative_models.py
> Make printing less verbose.

- google/generativeai/types/file_types.py
- tests/test_files.py
> Add video metadata and error to File

- google/generativeai/types/safety_types.py
- tests/test_generative_models.py
- tests/test_safety.py
generate_content(safety_setting='BLOCK_NONE')
> Quick safety filtering: Allow `safety_settings="block_none"`

- google/generativeai/generative_models.py
- tests/test_generative_models.py
Needs tests.
Fixes: https://github.com/google-gemini/generative-ai-python/issues/335
> Add request options to chat.

- google/generativeai/types/content_types.py
- tests/test_content.py
fixes: https://github.com/google-gemini/generative-ai-python/issues/160
> Handle image mode

- google/generativeai/caching.py
- google/generativeai/client.py
- google/generativeai/generative_models.py
- google/generativeai/types/caching_types.py
- setup.py
- tests/test_caching.py
- tests/test_generative_models.py
Change-Id: I694545243efda467d6fd599beded0dc6679b727d
===DO NOT SUBMIT===
*Inital prototype for explicit caching
*Add basic **CURD** support for caching
*Remove `INPUT_ONLY` marked fields from `CachedContent` dataclass
*Rename files `cached_content*` -> `caching*`
*Update `create` method for explicit instantination of 'CachedContent'
*Add a factory method to instatinate model with `CachedContent` as its context
*blacken
*Add tests
*Rename `get_cached_content` -> `get`
*Stroke out functional approach for `CachedContent` **CURD** ops
*Validate `name` checks for `CachedContent` creation
*Update repr for `GenerativeModel` to include information about the model's context
*Update docstrings
*Improve tests
> Explicit Caching

- tests/test_async_code_match.py
- tests/test_generative_models.py
- Allow async-code-match to consider methods starting with `_` (this is done to handle methods like `_handle_afc` and its async counterpart)
- Remove duplicate tests
> Remove duplicate test

- google/generativeai/__init__.py
Fix wrong argument in `__init__.py` which shows up on the [website](https://ai.google.dev/api/python/google/generativeai).
The example on the documentation is not working.
Bug fix
- [ x ] I have performed a self-review of my code.
- [ x ] I have added detailed comments to my code where applicable.
- [ x ] I have verified that my change does not break existing code.
- [ x ] My PR is based on the latest changes of the main branch (if unsure, please run `git pull --rebase upstream main`).
- [ x ] I am familiar with the [Google Style Guide](https://google.github.io/styleguide/) for the language I have coded in.
- [ x ] I have read through the [Contributing Guide](https://github.com/google/generative-ai-python/blob/main/CONTRIBUTING.md) and signed the [Contributor License …
> fix genai.GenerativeModel argument name in example

- samples/chat.py
Chat samples for:
* chat 
* chat with streaming
* chat with image and streaming
> Add samples for chat

- README.md
Adding a note about free tier not available in Europe
To clarify things for users and align with the other languages.
Choose one: Documentation
> Adding a note about free tier not available in Europe

- google/generativeai/types/content_types.py
Imports `PIL.PngImagePlugin` that was assumed to be loaded as part of PIL but isn't guaranteed to be loaded before this code is called. 
Adds an import statement to avoid an error when PIL is partially loaded resulting in the following error: `AttributeError: module 'PIL' has no attribute 'PngImagePlugin'`. This was already mentioned but not resolved in #178. 
Bug Fix
Fixes: #178
> Add PngImagePlugin to imports.

- samples/count_tokens.py
Ref: https://docs.google.com/document/d/1sWENsrragV8zjy1u9PC905maMPCnnq_AMo0uwa_omO4/edit?tab=t.0
> Sync count tokens examples

- samples/code_execution.py
Covers:
* code_execution_basic
* code_execution_request_override
* code_execution_chat
> Add code execution python sample

- samples/code_execution.py
> Format code execution

- samples/count_tokens.py
Formatting count_token.py using black
Passing checks so that all subsequent PR don't become blocked
Bug fix
> Formatting count tokens

- README.md
- google/generativeai/client.py
- google/generativeai/types/discuss_types.py
Instead of using the `GOOGLE_API_KEY` by default, we're checking for the `GEMINI_API_KEY` ones first since its naming is less misleading. The `GOOGLE_API_KEY` is still kept for consistency.
The Google API key can be misleading since it's not really an overall key for all of Google API and only for the Gemini ones.
Choose one: Feature request
> Using the `GEMINI_API_KEY` by default instead of the `GOOGLE_API_KEY` one

- .github/workflows/samples.yaml
- samples/rest/count_tokens.sh
- samples/rest/files.sh
Adding the following:
- files_create_pdf
- tokens_context_window
- tokens_cached_content
- tokens_system_instruction
- tokens_tools
> Add additional functions to files & count_tokens.

- CONTRIBUTING.md
The rendering is broken due to the missing closing backticks.
> Fix the missing closing backticks in CONTRIBUTING

- README.md
The region coverage is subject to change as we are rolling out AI Studio to more regions like the UK and EU. Users will be pointed to https://ai.google.dev/gemini-api/docs/available-regions if they are located in a region that is not yet supported.
We won't be able to maintain outdated documents on READMEs moving forward, so please either don't mention some of the operational details that are subject to change or provide a link to the official docs.
> Avoid making recommendations about regions in README

- google/generativeai/client.py
Fix files client to handle metadata and default_metadata.
> Fix default_metadata for files API.

- tests/test_helpers.py
- tests/test_protos.py
- tests/test_responder.py
When we run tests internally that don't invoke the test class, they pass but don't run the tests.
Our GitHub environment tests them fine but this change ensures they run in both environments.
I also removed unused imports in these files.
> Ensure tests are runnable when standalone

- google/generativeai/types/generation_types.py
- google/generativeai/types/model_types.py
- setup.py
- tests/test_files.py
- tests/test_generation.py
- tests/test_generative_models.py
> Add rev14 parameters and fixes.

- google/generativeai/py.typed
- setup.py
Add py.typed file to package
Without the py.typed, the library is considered untyped by type-checkers such as MyPy. 
Other
> feat: add py.typed

- google/generativeai/client.py
Added threading support to `FileServiceClient` to make `discovery_api` thread-local.
Fixes a threading issue where multiple threads could simultaneously access `self._discovery_api`, leading to bugs. Making `discovery_api` thread-local gives each thread its own instance.
**Resolves:** #327 
Bug fix
> fix: thread-safe discovery API setup (Issues#327)

- samples/rest/code_execution.sh
Use double-quoted string instead of single-quoted string in JSON.
The string 'code_execution' is unexpectedly single-quoted in a JSON string when it should be double-quoted. Apparently this still works for the API (as does not quoting the object key at all) but the Bash syntax highligher is confused and thinks that the 'code_execution' text is not part of the string.
> ![image](https://github.com/user-attachments/assets/96d4e803-bf59-4e02-968d-eb7222215396)
Choose one: Documentation
> Use double quotes for JSON object keys

- google/generativeai/client.py
- google/generativeai/types/content_types.py
- google/generativeai/types/image_types/__init__.py
- google/generativeai/types/image_types/_image_types.py
- google/generativeai/vision_models/__init__.py
- google/generativeai/vision_models/_vision_models.py
- tests/test_content.py
Allow generate_content to take generated images as input. 
Refactor some of the image classes into the same place. 
Build on `watermark` #603
- `client.py` - Move the `Value` management code to a PredictionServiceClient class.
- `content_types.py`, `image_types.py`
- Move image management code to `image_types`. 
- Add a handler for `(Generated)Image` objects for easy `Imagen` -> `GenerateContent`.  https://github.com/google-gemini/generative-ai-python/pull/608/files#diff-3e07c74e6bfc1479b6917014713aed0df6efda3eef780aa71061c0b688805b57R92-R93
> Image feedback

- samples/rest/text_generation.sh
This PR fixes the "argument list too long" error in the `text_generation.sh` file when using large base64 encoded images by using temporary files to store the encoded data and the JSON payload. This resolves issues encountered when running the `text_gen_multimodal_one_image_prompt` and `text_gen_multimodal_one_image_prompt_streaming` examples.
This PR also makes the following additions and updates:
- Adds two new multimodal vision examples to `text_generation.sh`:
- `text_gen_multimodal_two_image_prompt`: Demonstrates using two images in a single prompt.
- `text_gen_multimodal_one_image_bounding_box_prompt`: Shows how to generate bounding boxes for objects.
- Updates the `text_gen_multimodal_video_prompt` example: The prompt is now more comprehensive and does a better job demonstrating …
> Fix arg length error, add multimodal examples, update video prompt

- docs/ais-templates/aistudio_gemini_prompt_freeform.ipynb
- docs/ais-templates/aistudio_gemini_prompt_freeform_nofiles.ipynb
Copied from:
https: //github.com/google-gemini/cookbook/tree/e2623e8587f3d4ae13df65f415a3337c7f7ac97e/templates
Submit with https://github.com/google-gemini/cookbook/pull/325
> Copy AIS templates from cookbook.

- google/generativeai/types/model_types.py
Embedding model requires to mention as "models/<model_name>" but not other generative models which is simply "<model_name>"
It just for consistency of model usage. May fix #640.
Feature request
- I have performed a self-review of my code.
- I have added detailed comments to my code where applicable.
- I have verified that my change does not break existing code.
- My PR is based on the latest changes of the main branch (if unsure, please run `git pull --rebase upstream main`).
- I am familiar with the [Google Style Guide](https://google.github.io/styleguide/) for the language I have coded in.
- I have read through the [Contributing Guide](https://github.com/google/generative-ai-python/blob/main/CONTRIBUTING.md) and signed the [Contributor License …
> Refactor embedding model name in call

- docs/api/google/generativeai/protos/GenerationConfig.md
Fixed typo in Frequency Penalty description by changing "dificult" to "difficult".
Fixed an unfortunate misspelling of the word "difficult". The current documentation spells the word as "dificult" (one 'f') when the correct spelling is "difficult" (two 'f').
Implementing this change will improve the professionalism of the documentation and prevent readers from being caught off guard/distracted by the misspelling of a word.
Documentation
- [ x] I have performed a self-review of my code.
- [ x] I have added detailed comments to my code where applicable.
- [ x] I have verified that my change does not break existing code.
- [ x] My PR is based on the latest changes of the main branch (if unsure, please run `git pull --rebase upstream main`).
- [ x] I am familiar with the [Google Style …
> Update GenerationConfig.md to fix typo

- .github/workflows/user-input.yml
A new comment on an issue with this label would get the label automatically removed.
> Add a GitHub Action to manage status: `awaiting user response`

- .github/workflows/labeler.yml
- .github/workflows/remove-issue-labels.yml
- .github/workflows/remove-pr-labels.yml
- .github/workflows/samples.yaml
- .github/workflows/stale.yml
- .github/workflows/test_pr.yaml
[Security response](https://www.wiz.io/blog/github-action-tj-actions-changed-files-supply-chain-attack-cve-2025-30066) and [best practice](https://docs.github.com/en/actions/security-for-github-actions/security-guides/security-hardening-for-github-actions#using-third-party-actions)
Turns out versions are mutable, despite being tags.
> Pin actions to specific SHAs
