- google/generativeai/client.py
This will ensure things show up in the various dashboards.
Tested with a proxy: https://screenshot.googleplex.com/74xARBkr67VdrVy
Change-Id: I6af04cc078a84866f0a0d6c84f6686323bff7447
> Add user-agent to clientinfo

- setup.py
This is needed for the notebook/magics tests.
Change-Id: I28721edb6356ca9c47934f2c12c823a011a074b3
> Add `pandas` to dev deps

- google/generativeai/types/text_types.py
Fixes `TypeError: 'type' object is not subscriptable` error on import.
> bugfix: type list to List

- google/generativeai/text.py
https://developers.generativeai.google/api/python/google/generativeai/generate_text
> Fix broken generate_text doc page.

- google/generativeai/version.py
I'll make another release after tagging this.
> Update version.py 

- .github/workflows/test_pr.yaml
Test all supported python versions.
(Tested on my fork.)
> Add a GH action to run the tests.

- google/generativeai/__init__.py
- google/generativeai/client.py
- google/generativeai/discuss.py
- google/generativeai/docstring_utils.py
- google/generativeai/models.py
- google/generativeai/notebook/__init__.py
- google/generativeai/notebook/flag_def.py
- google/generativeai/notebook/lib/llm_function.py
- google/generativeai/notebook/lib/llm_function_test.py
- google/generativeai/notebook/lib/llmfn_input_utils.py
- google/generativeai/notebook/text_model.py
- google/generativeai/text.py
- google/generativeai/types/citation_types.py
- google/generativeai/types/model_types.py
- google/generativeai/types/safety_types.py
- google/generativeai/types/text_types.py
- google/generativeai/version.py
Resubmit of  #37.
For #38 
Pytype passes with python3.10, tests still pass with python3.9.
> Fix pytype

- .github/workflows/test_pr.yaml
> Add PyType presubmit for Py3.10

- google/generativeai/text.py
- google/generativeai/types/safety_types.py
- tests/test_text.py
> Allow more flexible safety_settings.

- google/generativeai/discuss.py
I would like to suggest a few modifications to make the user experience of `chat` and `chat_async` more similar.
> Refactor async chat code

- google/generativeai/__init__.py
> Add 'import os'

- setup.py
- tests/test_discuss_async.py
The first commit is the actual fix.
The second just formatting changes.
Fixes b/278080256
> Remove asynctest dependancy.

- .github/workflows/test_pr.yaml
- RELEASE.md
- google/generativeai/version.py
- setup.py
> Release 0.2.2

- README.md
> Fix MM snippet in README

- CONTRIBUTING.md
Corrected some typos in CONTRIBUTING.md.
I was going through the documentation and found this typo.
Documentation
> Corrected some typos

- README.md
Fix: update links to https://github.com/google/generative-ai-docs in the [Readme](https://github.com/google/generative-ai-python/blob/main/RELEASE.md)
Choose one: Documentation
> fix: update links to https://github.com/google/generative-ai-docs in the readme

- google/generativeai/generative_models.py
Simply correct a minor typo errors in comments at class GenerativeModel.
To provide smooth hands on Genmini experience for anyone who don't have much coding experience.
Choose one: Documentation
- [x ] I have performed a self-review of my code.
- [x ] I have added detailed comments to my code where applicable.
- [x ] I have verified that my change does not break existing code.
- [x ] My PR is based on the latest changes of the main branch (if unsure, please run `git pull --rebase upstream main`).
- [x ] I am familiar with the [Google Style Guide](https://google.github.io/styleguide/) for the language I have coded in.
- [ x] I have read through the [Contributing Guide](https://github.com/google/generative-ai-python/blob/main/CONTRIBUTING.md) and signed the [Contributor License …
> Update tutorial comments in class GenerativeModel

- setup.py
> fix: lock google-auth version to fix #114

- docs/build_docs.py
> Format build_docs.py

- google/generativeai/generative_models.py
- tests/test_generative_models.py
- tests/test_generative_models_async.py
Updated some test references too.
> Rename model defaults to use gemini-pro

- google/generativeai/types/retriever_types.py
- tests/test_retriever.py
- tests/test_retriever_async.py
> Wrapping `glm.RelevantChunk` as a class 

- google/generativeai/client.py
- google/generativeai/permission.py
- google/generativeai/types/permission_types.py
- google/generativeai/types/retriever_types.py
- tests/test_permission.py
- tests/test_permission_async.py
Permission module for Corpora resource.
> Permissions module

- google/generativeai/version.py
> Update version to 0.4.0

- docs/build_docs.py
> Debug the docs build.

- google/generativeai/types/answer_types.py
- google/generativeai/types/content_types.py
- google/generativeai/types/file_types.py
- google/generativeai/types/generation_types.py
- tests/test_typing_extensions.py
FIx TypedDict imports, and add a test.
Fixes: https://github.com/google/generative-ai-python/issues/209
> Import cleanup

- google/generativeai/types/content_types.py
I've eliminated duplicate branch condition checks and resolved an issue where glm.FunctionResponse was not functioning in the to_part method.
It will cause `to_part` method returns an incorrect result.
Choose one: Bug fix
> fix: incorrect type checking

- google/generativeai/embedding.py
- tests/test_embedding.py
- tests/test_embedding_async.py
1. Add support for `QUESTION_ANSWERING` and `FACT_VERIFICATION` task types for embeddings.
2. Add `output_dimensionality` param to `genai.embed_content` methods.
> Support for new `TaskTypes` and `output_dimensionality` param

- google/generativeai/client.py
Fixes: https://github.com/google-gemini/generative-ai-python/issues/292
> Fix file uploads

- google/generativeai/permission.py
- google/generativeai/types/model_types.py
- google/generativeai/types/permission_types.py
- google/generativeai/types/retriever_types.py
- tests/test_async_code_match.py
- tests/test_permission.py
- tests/test_permission_async.py
Implement **Permission service** for Tuned Model
> Extend permissions service support to Tuned Models 

- google/generativeai/client.py
> Use api_endpoint for uploads

- google/generativeai/__init__.py
Move the example to use Gemini 1.5 Flash
> Update __init__.py to use the latest model

- setup.py
- tests/test_generative_models.py
- tests/test_generative_models_async.py
Change-Id: Idd9b450daf8b0b2b09a07127aaa37f97e8b8cfbf
We need to merge this before #377
> Update gapic lib to use 0.6.5 and fix tests

- tests/test_generative_models.py
- tests/test_generative_models_async.py
Remove references to pro-vision.
> remove references to pro-vision

- google/generativeai/files.py
Adds prefix `files/` if not present
Fix types
Change-Id: Iac5c4d0934620f2462cf15ae519474b0ce7908da
> Accept partial file names

- samples/embed.py
Sample code for embeddings, with UnitTest.
> Add embedding sample

- samples/embed.py
- samples/json_mode.py
Add sample code for JSON mode.
> Add sample for JSON controlled generation

- google/generativeai/types/content_types.py
- google/generativeai/types/generation_types.py
- google/generativeai/version.py
- setup.py
- tests/test_content.py
- tests/test_generation.py
Code execution feature for Gemini API, including test cases.
> Code execution

- samples/cache.py
- samples/embed.py
- samples/files.py
- samples/json_mode.py
- third_party/LICENSE.txt
- third_party/a11.txt
Samples for caching:
- create
- delete
- list
- update
- get
Added `a11.txt` for ease of use.
> Caching samples

- samples/text_generation.py
Matching what's in the Android PR for `text_generation`. (https://github.com/google-gemini/generative-ai-android/pull/182/files#diff-d9764ba61dd5ff3c726e53a542c626b7259d3086cf61137b865283d3ec0eee06)
> Update text only prompts

- .github/workflows/test_pr.yaml
Trigger tests and formatting when samples/ are updated.
> format-samples

- samples/model_configuration.py
Model configuration sample based on https://ai.google.dev/gemini-api/docs/get-started/tutorial?lang=python#generation_configuration
> Add model configuration sample

- google/generativeai/files.py
- tests/test_files.py
Fixes: https://github.com/google-gemini/generative-ai-python/issues/425
> Add webp to mimetypes

- samples/code_execution.py
This is important so you know if the code was actually run or not.
> Update example to show part types.

- samples/rest/embeddings.sh
- samples/rest/system_instruction.sh
- samples/system_instruction.py
Adding REST embeddings sample for `embed` and `batch_embed`. 
Also adding the system_instruction sample as well here because I forgot to make a new branch - sorry!
Do we need to demonstrate `output_dimensionality` and `task_type` in this sample as well?
> Add REST embeddings & system_instruction sample

- samples/rest/code_execution.sh
> Code execution for shell

- samples/controlled_generation.py
Fixes: https://github.com/google-gemini/generative-ai-python/issues/497
> Fix response_schema sample.

- google/generativeai/notebook/cmd_line_parser.py
Fixes: https://github.com/google-gemini/generative-ai-python/issues/520
> Fix tests for 3.12.5

- google/generativeai/version.py
- setup.py
0.6.10 is out:
https://pypi.org/project/google-ai-generativelanguage/#history
> Update to use google.generativelanguage 0.6.10.

- google/generativeai/types/generation_types.py
Fixes: https://github.com/google-gemini/generative-ai-python/issues/559
> Remove finish_message

- samples/rest/function_calling.sh
> Fix function_calling.sh example

- .github/workflows/user-input.yml
Update user-input.yml GitHub workflow to trigger additionally on PR comments.
For easier triaging of open pull requests.
Other
> chore: Update user-input.yml GitHub workflow to trigger on PR comments
